name: pokemon
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.13.5
  firebase_dynamic_links: ^0.5.0+9
  flare_flutter: ^1.8.3
  provider: ^4.0.0
  share: ^0.6.3+5
  shared_preferences: ^0.5.6
  socket_io_client: ^0.9.7+2
  url_launcher: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/flare/
    - assets/image/
    - assets/sound/
    - assets/target/
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/font/quicksand.ttf
